- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update
    become : yes
   
    
  - name : Install Docker
    command :  sudo apt-get install -y docker.io
    become : yes
    

  - name : Start Docker Service
    command : sudo systemctl start docker
    become : yes
   
    
  - name: Deploy Docker Container
    command: docker run -itd -p 8082:8081 udaydocker123/medicureproject:latest
